[package]
name = "cartomata"
authors = ["piface314"]
license = "MIT"
version = "0.1.0"
edition = "2021"
description = ""

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
csv = "1.3.0"
itertools = "0.12.1"
mlua = { version = "0.9.6", features = ["lua54", "vendored"] }
ril = { git = "https://github.com/piface314/ril.git", version = "^0.11.0-beta.0", features = ["all"] }
serde = { version = "1.0.197", features = ["derive", "serde_derive", "std"] }
sqlite = "0.34.0"
toml = "0.8.12"
